project_id = "ffysrimclqdhdytqfidj"

[functions.check-rate-limit]
verify_jwt = false

[functions.enviar-lembretes]
verify_jwt = false

[functions.lembrete-medidas]
verify_jwt = false

[functions.lembrete-alongamento]
verify_jwt = false

[functions.gerar-recomendacoes]
verify_jwt = false

[functions.notificacoes-inteligentes]
verify_jwt = false

[functions.enviar-whatsapp]
verify_jwt = false

[functions.gerar-imagem-servico]
verify_jwt = false

[functions.enviar-campanha]
verify_jwt = false